[package]
name = "terra-asset"
description = "Helper library for interacting with Terra assets (SDK coins and CW20 tokens)"
version = "0.1.0"
authors = ["larry <larry@delphidigital.io>"]
edition = "2018"
license = "GPLv3-or-later"
repository = "https://github.com/larry0x/terra-asset"

[lib]
doctest = false # do not run doc tests

[dependencies]
cosmwasm-std = "0.16.0"
cw20 = "0.9.1"

terra-cosmwasm = "2.2.0"

schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = "1.0.23"