[package]
name = "cw-asset"
description = "Helper library for interacting with Cosmos assets (SDK coins and CW20 tokens)"
version = "2.0.0"
authors = ["larry <larry@delphidigital.io>"]
edition = "2018"
license = "GPL-3.0-or-later"
repository = "https://github.com/mars-protocol/cw-asset"

[dependencies]
cosmwasm-std = "1.0"
cw20 = "0.13"
cw-storage-plus = "0.13"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
